name: Check

on:
  push:
    branches: [ master ]
    tags: [ '*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]
        r-version: [ 3.6, oldrel, release, devel ]
        include:
        - os: windows-2022
          r-version: devel-ucrt

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-R${{ matrix.r-version }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      # r-lib/setup-r doesn't setup UCRT properly (yet)
      - if: ${{ matrix.r-version != 'devel-ucrt' }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - if: ${{ runner.os == 'Windows' && matrix.r-version == 'devel-ucrt' }}
        uses: kalibera/ucrt3/actions/r-install@main
      - if: ${{ runner.os == 'Windows' && matrix.r-version == 'devel-ucrt' }}
        uses: kalibera/ucrt3/actions/toolchain-install@main
        with:
          toolchain-type: base

      - uses: s-u/R-actions/pkg-check@master
        with:
          check-flags: --as-cran
