name: Check

on:
  push:
    branches: [ master ]
    tags: [ '*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]
        r-version: [ 3.6, oldrel, release, devel ]

    env:
      debian-deps: libssl-dev libcurl4-openssl-dev
      macos-deps: openssl-1.1.1h
      windows-deps: openssl

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-R${{ matrix.r-version }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      # From https://github.com/s-u/R-actions/blob/master/pkg-check/action.yml
      - name: Install Linux dependencies
        if: ${{ runner.os == 'Linux' && env.debian-deps != '' }}
        run: |
            echo "::group::Install Linux system dependencies"
            sudo apt-get install -y ${{ env.debian-deps }}
            echo '::endgroup::'
        shell: bash
      - name: Install macOS dependencies
        if: ${{ runner.os == 'macOS' && env.macos-deps != '' }}
        run: |
            echo "::group::Install macOS system dependencies"
            for i in ${{ env.macos-deps }}; do
              echo -n "  $i"
              curl -s https://mac.r-project.org/libs-4/$i-darwin.17-x86_64.tar.gz | sudo tar fxz - --strip 2 -C /usr/local
            done
            echo ''
            echo '::endgroup::'
        shell: bash
      - name: Install Windows dependencies
        if: ${{ runner.os == 'Windows' && env.windows-deps != '' }}
        run: |
            choco install msys2 --params "/NoUpdate"
            echo "C:\\tools\\msys64\\usr\\bin" >> $GITHUB_PATH
            echo "C:\\tools\\msys64\\mingw64\\bin" >> $GITHUB_PATH
            echo "PKG_CONFIG_PATH=/mingw64/lib/pkgconfig" >> $GITHUB_ENV
            pacman -Sy --noconfirm pacman
            pacman -S --noconfirm pacman-mirrors pkg-config
            pacman -S --noconfirm --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain mingw-w64-x86_64-openssl upx
            echo "::group::Install Windows system dependencies"
            if which pacman 2>/dev/null; then
              pacman -Sy
              for i in ${{ env.windows-deps }}; do
                pacman --sync --noconfirm mingw-w64-i686-$i mingw-w64-x86_64-$i
              done
            else
              echo "NOTE: pacman not found, assuming UCRT toolchain which already contains dependencies"
              echo "      see https://github.com/kalibera/ucrt3 for corresponding action"
            fi
            echo ''
            echo '::endgroup::'
        shell: bash

      - if: ${{ runner.os != 'Windows' }}
        run: |
            "bash -c 'java -version && which java && echo $PATH && echo $JAVA_HOME'"
            "echo export PATH=$PATH > reconf.sh; echo export JAVA_HOME=$JAVA_HOME >> reconf.sh; echo R CMD javareconf >> reconf.sh; sudo bash reconf.sh"

      - run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"

      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-${{ matrix.os }}-R${{ matrix.r-version }}
          path: |
            *.txt
            *.log
            *.out
            *.Rout

      - uses: s-u/R-actions/pkg-check@master
        with:
          check-flags: --as-cran
