name: Check

on:
  push:
    branches: [ master ]
    tags: [ '*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]
        r-version: [ 3.6, oldrel, release, devel ]

    env:
      debian-deps: libssl-dev libcurl4-openssl-dev
      macos-deps: openssl-1.1.1h
      windows-deps: openssl

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-R${{ matrix.r-version }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}

      # From https://github.com/s-u/R-actions/blob/master/pkg-check/action.yml
      - name: Install Linux dependencies
        if: ${{ runner.os == 'Linux' && env.debian-deps != '' }}
        run: |
            echo "::group::Install Linux system dependencies"
            sudo apt-get install -y ${{ env.debian-deps }}
            echo '::endgroup::'
        shell: bash
      - name: Install macOS dependencies
        if: ${{ runner.os == 'macOS' && env.macos-deps != '' }}
        run: |
            echo "::group::Install macOS system dependencies"
            for i in ${{ env.macos-deps }}; do
              echo -n "  $i"
              curl -s https://mac.r-project.org/libs-4/$i-darwin.17-x86_64.tar.gz | sudo tar fxz - --strip 2 -C /usr/local
            done
            echo ''
            echo '::endgroup::'
        shell: bash
      - if: ${{ runner.os == 'Windows' }}
        run: |
          echo "C:\rtools" >> $GITHUB_PATH
          echo "C:\rtools40" >> $GITHUB_PATH
        shell: bash
      - name: Install Windows dependencies
        if: ${{ runner.os == 'Windows' && env.windows-deps != '' }}
        run: |
            echo "::group::Install Windows system dependencies"
            mingw32.exe pacman -Sy
            mingw64.exe pacman -Sy
            for i in ${{ env.windows-deps }}; do
              echo -n "  $i"
              mingw32.exe pacman --sync --noconfirm mingw-w64-i686-$i
              mingw64.exe pacman --sync --noconfirm mingw-w64-x86_64-$i mingw-w64-i686-$i
            done
            echo ''
            echo '::endgroup::'
        shell: bash

      - if: ${{ runner.os == 'macOS' }}
        run: echo "/Library/Frameworks/R.framework/Resources/bin" >> $GITHUB_PATH
      - if: ${{ runner.os != 'Windows' }}
        run: sudo R CMD javareconf
        shell: bash

      - run: Rscript -e "install.packages('remotes', repos = 'https://cloud.r-project.org')" -e "remotes::install_deps(dependencies = TRUE)"

      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-${{ matrix.os }}-R${{ matrix.r-version }}
          path: |
            *.txt
            *.log
            *.out
            *.Rout

      - uses: s-u/R-actions/pkg-check@master
        with:
          check-flags: --as-cran --no-multiarch
