name: Examples

on:
  push:
    branches: [ master ]
    tags: [ '*.*' ]
  pull_request:
    branches: [ master ]
    
jobs:
  examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        R: [3.6, 4.0, 4.1]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.R }}
    - if: matrix.os == 'macos-latest'
      run: brew install automake
    - if: matrix.os == 'macos-latest' && matrix.R == '3.6'
      run: ln -s /Library/Frameworks/R.framework/Versions/3.6 /Library/Frameworks/R.framework/Versions/3.5
    - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: sudo R CMD javareconf  
    - if: matrix.os == 'ubuntu-latest' 
      run: sudo apt install -y libcurl4-openssl-dev
    - run: Rscript -e "install.packages('devtools',repos='https://cloud.r-project.org'); devtools::install_github('Funz/Funz.R',INSTALL_opts=c('--no-multiarch'))" > install.Rout
      shell: bash
    - run: Rscript -e "library('Funz'); calcs = startCalculators(5); Sys.sleep(5); Run(model = 'R',input.files = file.path(Funz:::FUNZ_HOME,'samples','branin.R'),input.variables = list(x1=seq(0,1,by=0.1),x2=seq(0,1,by=0.1)),all.combinations=TRUE,output.expressions = 'z'); stopCalculators(calcs)" > Run.Rout
      shell: bash
    - run: Rscript -e "library('Funz'); install.Design('GradientDescent'); Design(fun = function(X){colnames(X)=c('x1','x2');print(X);abs(X$x1*X$x2)}, design = 'GradientDescent', options = list(max_iterations=10),input.variables = list(x1='[0,1]',x2='[1,2]'))" > Design.Rout
      shell: bash
    - run: Rscript -e "library('Funz'); install.Design('GradientDescent'); startCalculators(5); Sys.sleep(5); RunDesign(model='R',input.files=file.path(Funz:::FUNZ_HOME,'samples','branin.R'),output.expressions='cat', design = 'GradientDescent',design.options = list(max_iterations=10),input.variables = list(x1='[0,1]',x2='[0,1]')); stopCalculators(calcs)" > RunDesign.Rout
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        path: ./*.Rout
